[project]
name = "databaseandwebsitebackup"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "boto3>=1.40.9",
    "boto3-stubs==1.40.53",
    "humanize>=4.12.3",
    "types-boto3[s3]>=1.40.54",
]
