[project]
name = "databaseandwebsitebackup"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "boto3>=1.40.9",
    "humanize>=4.12.3",
    "schedule>=1.2.2",
    "types-boto3[s3]>=1.41.1",
]
